apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: analy
  namespace: monitoring
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          imagePullSecrets:
          - name: registry-pull-secret
          restartPolicy: Never
          containers:
          - name: analy
            image: swr.cn-north-4.myhuaweicloud.com/cotte-bigdata/analy:0.0.1628580053
            imagePullPolicy: Always
            env:
            - name: ANALY_HOME
              value: /opt/analy/
            command:
            - python3
            args:
            - "/opt/analy/src/core/run.py"
            - "--core.run.step=forecast"
            - "--env=prod"
            volumeMounts:
            - mountPath: /opt/analy/src/result/
              name: result
          volumes:
          - name: result
            persistentVolumeClaim:
              claimName: efs-result
