apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-class: object
    volume.beta.kubernetes.io/storage-provisioner: ceph.com/cephfs
  name: object
  namespace: paddle
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
