kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: object
provisioner: ceph.com/cephfs
parameters:
    monitors: 172.16.7.170:6789
    adminId: admin
    adminSecretName: ceph-secret-170
    adminSecretNamespace: "storage"
    claimRoot: /volumes/kubernetes/paddle/object/

