#FROM python:3.8.5
FROM swr.cn-north-4.myhuaweicloud.com/cotte-bigdata/ubuntu20-python3:v3.8.10
ARG CONTAINERNAME
RUN pip install paddlepaddle-gpu==2.1.0 -i https://mirror.baidu.com/pypi/simple
#RUN pip install paddlepaddle-gpu==2.1.0
RUN pip install numpy==1.21.0
RUN pip install opencv-python==4.5.2.54
RUN pip install pandas==1.2.5
RUN pip install matplotlib==3.4.2
RUN pip install tqdm==4.61.1
RUN pip install mysql-connector==2.2.9
RUN pip install sqlalchemy==1.4.20
